theme: jekyll-theme-minimal
logo: 
title: Learn SDR
description: Harvey Mudd College
show_downloads: true
google_analytics:
relative_links:
  enabled:     true
  collections: false
highlighter: rouge
markdown: kramdown
kramdown:
  parse_block_html: true
